### ISSUE TITLE
[tracker] what needs to be translated #5

### ISSUE THREAD

**Issue by bekcpear** [plctlab/rvspoc#128]
本届锦标赛接近了尾声，更新了获奖相关的信息，有两个零碎的内容需要翻译/确认一下，以使网站更加完整。

## 结果公示的 banner 内容

> 本次锦标赛的获奖结果已公布，公示期为 2024 年 4 月 3 日 —— 2024 年 4 月 10 日。

- [x] English https://github.com/plctlab/rvspoc/blob/717b21f4dbdc9cd2560244af16c5ab7cfb5b37e9/hugo.toml#L81
- [x] Russian https://github.com/plctlab/rvspoc/blob/717b21f4dbdc9cd2560244af16c5ab7cfb5b37e9/hugo.toml#L97
- [ ] (outdated after 2024-04-11) ~~Japanese https://github.com/plctlab/rvspoc/blob/717b21f4dbdc9cd2560244af16c5ab7cfb5b37e9/hugo.toml#L115~~
- [ ] (outdated after 2024-04-11) ~~Korean https://github.com/plctlab/rvspoc/blob/717b21f4dbdc9cd2560244af16c5ab7cfb5b37e9/hugo.toml#L133~~

---

## 首页的点击按钮

2024-04-11 更新：更新需求为「冠军名单」

1. ~~等待一周公示期结束之后，可能会需要额外更新首页的点击按钮，预测的更新后内容为「冠军名单」，还需要麻烦在 PR 的时候，把这个翻译内容放在 PR 的评论内，方便下次直接使用~~
2. ~~当前的内容也需要翻译，翻译取词可以是：~~
   * ~~「锦标赛获奖结果公示」~~
   * ~~「获奖结果公示」~~
   * ~~「冠军名单已公示」~~
   ~~意思能表达到是公布/公示这件事即可。~~

   位置：

   - [x] English https://github.com/plctlab/rvspoc/blob/89682735e75f375177d37229b3b2b70d15c95080/i18n/en.toml#L47
   - [x] Russian https://github.com/plctlab/rvspoc/blob/89682735e75f375177d37229b3b2b70d15c95080/i18n/ru.toml#L47
   - [x] Japanese https://github.com/plctlab/rvspoc/blob/89682735e75f375177d37229b3b2b70d15c95080/i18n/ja.toml#L56
   - [x] Korean https://github.com/plctlab/rvspoc/blob/89682735e75f375177d37229b3b2b70d15c95080/i18n/ko.toml#L47

---

**Comment by bekcpear** [comment]
Russian: #129

**Comment by bekcpear** [comment]
Optimized English Translation from @MingcongBai : #130

**Comment by bekcpear** [comment]
首页按钮内容更新： https://github.com/plctlab/rvspoc/pull/133/commits/dfb356b58781a98aa5c3d1063e1c693108b9a9bd
