### ISSUE TITLE
[tracker] what needs to be translated #1

### ISSUE THREAD

**Issue by bekcpear** [plctlab/rvspoc#17]
## English

- [x] README.en.md: https://github.com/plctlab/rvspoc/blob/main/README.en.md
- [x] i18n file: https://github.com/plctlab/rvspoc/blob/main/i18n/en.toml
- [x] index file for posts section: https://github.com/plctlab/rvspoc/tree/main/content/en/posts/_index.md
- [x] index file for challenges section: https://github.com/plctlab/rvspoc/tree/main/content/en/challenges/_index.md
- [x] introduction (draft?) https://github.com/plctlab/rvspoc/blob/main/content/en/introduction.md
- [x] challenges ( `{P,S}XXXX` ): https://github.com/plctlab/rvspoc/tree/main/content/en/challenges/

## Russian

- [x] README.ru.md: https://github.com/plctlab/rvspoc/blob/main/README.ru.md
- [x] i18n file: https://github.com/plctlab/rvspoc/blob/main/i18n/ru.toml
- [x] index file for posts section: https://github.com/plctlab/rvspoc/tree/main/content/ru/posts/_index.md
- [x] index file for challenges section: https://github.com/plctlab/rvspoc/tree/main/content/ru/challenges/_index.md
- [x] introduction (draft?) https://github.com/plctlab/rvspoc/blob/main/content/ru/introduction.md
- [x] challenges ( `{P,S}XXXX` ): https://github.com/plctlab/rvspoc/tree/main/content/ru/challenges/

## Japanese

- [x] README.ja.md: https://github.com/plctlab/rvspoc/blob/main/README.ja.md
- [x] i18n file: https://github.com/plctlab/rvspoc/blob/main/i18n/ja.toml
- [x] index file for posts section: https://github.com/plctlab/rvspoc/tree/main/content/ja/posts/_index.md
- [x] index file for challenges section: https://github.com/plctlab/rvspoc/tree/main/content/ja/challenges/_index.md
- [x] introduction (draft?) https://github.com/plctlab/rvspoc/blob/main/content/ja/introduction.md
- [x] challenges ( `{P,S}XXXX` ): https://github.com/plctlab/rvspoc/tree/main/content/ja/challenges/

## Korean

- [x] README.ko.md: https://github.com/plctlab/rvspoc/blob/main/README.ko.md
- [x] i18n file: https://github.com/plctlab/rvspoc/blob/main/i18n/ko.toml
- [x] index file for posts section: https://github.com/plctlab/rvspoc/tree/main/content/ko/posts/_index.md
- [x] index file for challenges section: https://github.com/plctlab/rvspoc/tree/main/content/ko/challenges/_index.md
- [x] introduction (draft?) https://github.com/plctlab/rvspoc/blob/main/content/ko/introduction.md
- [x] challenges ( `{P,S}XXXX` ): https://github.com/plctlab/rvspoc/tree/main/content/ko/challenges/

**Comment by bekcpear** [comment]
i18n fix-up, en, https://github.com/plctlab/rvspoc/pull/21

**Comment by bekcpear** [comment]
Russian completes https://github.com/plctlab/rvspoc/pull/30

**Comment by alapha23** [comment]
@bekcpear 
Raised [PR for Japanese](https://github.com/plctlab/rvspoc/pull/34/)
