### ISSUE TITLE
[tracker] what needs to be translated #2

### ISSUE THREAD

**Issue by bekcpear** [plctlab/rvspoc#59]
## English

- [ ] S2312.md (**⚠️HIGH PRIORITY**): https://github.com/plctlab/rvspoc/blob/main/content/en/challenges/S2312.md
- [ ] FAQ: https://github.com/plctlab/rvspoc/blob/main/content/en/faq.md
- [ ] CN Domestic GPUs: https://github.com/plctlab/rvspoc/blob/main/content/en/cn-domestic-gpu.md

---

## Russia

- [ ] S2312.md (**⚠️HIGH PRIORITY**): https://github.com/plctlab/rvspoc/blob/main/content/ru/challenges/S2312.md
- [ ] FAQ: https://github.com/plctlab/rvspoc/blob/main/content/ru/faq.md
- [ ] CN Domestic GPUs: https://github.com/plctlab/rvspoc/blob/main/content/ru/cn-domestic-gpu.md

---

## Japanese

- [ ] S2312.md (**⚠️ HIGH PRIORITY**): https://github.com/plctlab/rvspoc/blob/main/content/ja/challenges/S2312.md
- [ ] FAQ: https://github.com/plctlab/rvspoc/blob/main/content/ja/faq.md
- [ ] CN Domestic GPUs: https://github.com/plctlab/rvspoc/blob/main/content/ja/cn-domestic-gpu.md

---

## Korean

- [ ] S2312.md (**⚠️HIGH PRIORITY**): https://github.com/plctlab/rvspoc/blob/main/content/ko/challenges/S2312.md
- [ ] FAQ: https://github.com/plctlab/rvspoc/blob/main/content/ko/faq.md
- [ ] CN Domestic GPUs: https://github.com/plctlab/rvspoc/blob/main/content/ko/cn-domestic-gpu.md

**Comment by bekcpear** [comment]
Russia translation complete. #62

**Comment by alapha23** [comment]
Japanese translation added #65

**Comment by alapha23** [comment]
Korean translation added #66
