### ISSUE TITLE
[tracker] what needs to be translated #3

### ISSUE THREAD

**Issue by bekcpear** [plctlab/rvspoc#90]
Hi! 针对每个赛题的提交和验收说明进行了更新，赛题间绝大多数内容是相同的，但是 S 类赛题下，验收说明基本不同。请根据实际情况翻译一下。

每个赛题翻译完成之后，请删除对应的老的

<pre>
**验证平台** xxxxxxx

## 提交仓库

https://xxxxxxxxxxx
</pre>

说明。

**Edited:** 以及

- P2307
- P2308
- S2302
- S2305
- S2306
- S2309
- S2310
- S2311

这几个，最后有多了一个英文的额外资源说明，资源是中文的（视频直播地址和一点说明），也可以顺带翻译一下，不过翻译后，要带上类似 `（中文）` 这样的额外标记。

---

## English

Directory: https://github.com/plctlab/rvspoc/tree/main/content/en/challenges

- [x] P2301 OpenHarmony 在 SG2042 上的移植和演示
- [x] P2303 ROCm 平台移植并兼容 AMD GPU
- [x] P2304 国产 GPU 平台移植和演示
- [x] P2307 Zephyr 移植和演示
- [x] P2308 Xv6 移植和演示
- [x] S2302 二进制翻译及优化
- [x] S2306 Node.js 性能优化
- [x] S2305 OpenGauss 数据库移植和优化
- [x] S2309 OpenCV 在 Duo 上的速度优化
- [x] S2310 ncnn 移植和优化
- [x] S2311 Baby LLaMA 2 on Duo 速度优化（儿童讲故事场景）
- [x] S2312 流式 ASR 在 SG2002 上的移植优化

---

## Russian

Directory: https://github.com/plctlab/rvspoc/tree/main/content/ru/challenges

- [x] P2301 OpenHarmony 在 SG2042 上的移植和演示
- [x] P2303 ROCm 平台移植并兼容 AMD GPU
- [x] P2304 国产 GPU 平台移植和演示
- [x] P2307 Zephyr 移植和演示
- [x] P2308 Xv6 移植和演示
- [x] S2302 二进制翻译及优化
- [x] S2306 Node.js 性能优化
- [x] S2305 OpenGauss 数据库移植和优化
- [x] S2309 OpenCV 在 Duo 上的速度优化
- [x] S2310 ncnn 移植和优化
- [x] S2311 Baby LLaMA 2 on Duo 速度优化（儿童讲故事场景）
- [x] S2312 流式 ASR 在 SG2002 上的移植优化

---

## Japanese

Directory: https://github.com/plctlab/rvspoc/tree/main/content/ja/challenges

- [x] P2301 OpenHarmony 在 SG2042 上的移植和演示
- [x] P2303 ROCm 平台移植并兼容 AMD GPU
- [x] P2304 国产 GPU 平台移植和演示
- [x] P2307 Zephyr 移植和演示
- [x] P2308 Xv6 移植和演示
- [x] S2302 二进制翻译及优化
- [x] S2306 Node.js 性能优化
- [x] S2305 OpenGauss 数据库移植和优化
- [x] S2309 OpenCV 在 Duo 上的速度优化
- [x] S2310 ncnn 移植和优化
- [x] S2311 Baby LLaMA 2 on Duo 速度优化（儿童讲故事场景）
- [x] S2312 流式 ASR 在 SG2002 上的移植优化

---

## Korean

Directory: https://github.com/plctlab/rvspoc/tree/main/content/ko/challenges

- [x] P2301 OpenHarmony 在 SG2042 上的移植和演示
- [x] P2303 ROCm 平台移植并兼容 AMD GPU
- [x] P2304 国产 GPU 平台移植和演示
- [x] P2307 Zephyr 移植和演示
- [x] P2308 Xv6 移植和演示
- [x] S2302 二进制翻译及优化
- [x] S2306 Node.js 性能优化
- [x] S2305 OpenGauss 数据库移植和优化
- [x] S2309 OpenCV 在 Duo 上的速度优化
- [x] S2310 ncnn 移植和优化
- [x] S2311 Baby LLaMA 2 on Duo 速度优化（儿童讲故事场景）
- [x] S2312 流式 ASR 在 SG2002 上的移植优化

**Comment by bekcpear** [comment]
Russian translation: https://github.com/plctlab/rvspoc/pull/92

**Comment by bekcpear** [comment]
English translation: https://github.com/plctlab/rvspoc/pull/95

**Comment by alapha23** [comment]
#104 Japanese

**Comment by alapha23** [comment]
#105 Korean
