### ISSUE TITLE
[tracker] what needs to be translated #4

### ISSUE THREAD

**Issue by bekcpear** [plctlab/rvspoc#98]
有个关于比赛延期的消息，需要翻译一下。

文件位置为： https://github.com/plctlab/rvspoc/blob/main/hugo.toml

- [x] English https://github.com/plctlab/rvspoc/blob/b92c006e86895c8577c4ed3a54773e64889836f0/hugo.toml#L75
- [x] Russian https://github.com/plctlab/rvspoc/blob/b92c006e86895c8577c4ed3a54773e64889836f0/hugo.toml#L88
- [x] Japanese https://github.com/plctlab/rvspoc/blob/b92c006e86895c8577c4ed3a54773e64889836f0/hugo.toml#L103
- [x] Korean https://github.com/plctlab/rvspoc/blob/b92c006e86895c8577c4ed3a54773e64889836f0/hugo.toml#L118

**Comment by MingcongBai** [comment]
@bekcpear 其实英文中把 deadline of 改成 deadline for 就好了

**Comment by bekcpear** [comment]
Russian https://github.com/plctlab/rvspoc/pull/103

**Comment by alapha23** [comment]
https://github.com/plctlab/rvspoc/pull/119
